### ISSUE TITLE
Will these Authorize.NET changes affect this package?

### ISSUE THREAD

**Issue by chavenor** [jeffschenck/authorizesauce#32]
See image. 

![auth net](https://cloud.githubusercontent.com/assets/1850981/8993388/68e8a120-36ca-11e5-8fe3-e9d4708e2513.png)

**Comment by jeffschenck** [comment]
There's nothing that needs to be urgently fixed or changed based on this note they sent out. Basically, you can proactively upgrade to new Akamai-backed API endpoints that should make your API calls faster but otherwise work exactly the same. If you don't change anything at all, the existing API endpoints will be moved over to the new infrastructure in June 2016. 

As they point out at the bottom of the email, there are a few edge cases where switching endpoints might cause your integration to break. Given that fact, I wasn't planning to switch the endpoints in this project. For example, if someone's deploy process pip installs "authorizesauce>=0.3.3" and they have a particular firewall setup, then simply updating the endpoints and packaging it up on PyPI could break someone's deploys. 

If someone was interested in putting together a pull request that introduced a concept of configuration/settings into the project, which defaulted to the old endpoints but allowed specifying the new endpoints, I would be open to that.
